title: MICSO – Microbial Integration in Soil Systems
email: alberto.canarini@hotmail.it
description: Soil microbial ecology and biogeochemistry lab
baseurl: ""
url: "https://canarinialberto.com"

sass:
  style: compressed

minima:
  skin: custom

theme: minima

plugins: []

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
